### ISSUE TITLE
[Bug]: docker映射数据卷无法启动

### ISSUE THREAD

**Issue by LECYWZA** [oceanbase/docker-images#56]
### Describe the bug

```
services:
  oceanbase:
    image: oceanbase/oceanbase-ce:4.3.5-lts
    container_name: oceanbase-ce
    restart: unless-stopped
    ports:
      - "2881:2881"  # 暴露OceanBase的MySQL协议端口
    #environment:
      # 运行模式定义：mini(最小资源)/slim(快速启动)/normal(完整配置)
      # mini 表示容器将使用最少的资源
      # normal 表示容器将尽可能多地使用容器资源
      # slim 表示容器只会使用 fastboot 模式启动 Observer，tenant 命名为 test，tenant 和 resource 配置不会生效。
      #MODE: normal
      # 集群名称标识（仅小写字母和数字）
      #OB_CLUSTER_NAME: obcluster
      # MySQL兼容租户名称（slim模式强制使用test）
      #OB_TENANT_NAME: test
      # sys管理员密码
      #OB_SYS_PASSWORD: "sys@123456"
      # 业务租户root密码（建议与sys密码不同）
      #OB_TENANT_PASSWORD: "ewq@123456"
      # 集群总内存配额,默认6G（需>=OB_SYSTEM_MEMORY+OB_TENANT_MEMORY_SIZE）
      #OB_MEMORY_LIMIT: "6G"
      # 系统预留内存（建议总内存的10-20%）
      #OB_SYSTEM_MEMORY: "1G"
      # 数据文件初始大小（后期可动态扩展）
      #OB_DATAFILE_SIZE: "5G"
      # 日志磁盘空间（建议数据文件大小的1-2倍）
      #OB_LOG_DISK_SIZE: "5G"
      # 租户最小保障CPU核数（根据负载调整）
      # OB_TENANT_MINI_CPU: 2
      # 租户专属内存配额（需<=OB_MEMORY_LIMIT-OB_SYSTEM_MEMORY）
      # OB_TENANT_MEMORY_SIZE: 2G
      # 租户专属日志空间（需<=OB_LOG_DISK_SIZE）
      # OB_TENANT_LOG_DISK_SIZE: 8G
      # 启动失败处理策略（true:自动退出/false:保持运行）
      # EXIT_WHILE_ERROR: true
    volumes:
      - ./oceanbase/ob:/root/ob            # 数据目录
      - ./oceanbase/obd/cluster:/root/.obd/cluster  # 集群配置
    # - ./init_sql:/root/boot/init.d      # SQL初始化脚本目录（需.sql后缀）
````

注释掉数据卷配置才能启动
```
volumes:
      - ./oceanbase/ob:/root/ob            # 数据目录
      - ./oceanbase/obd/cluster:/root/.obd/cluster  # 集群配置
```

映射数据卷的时候日志: 第一次容器失败,第二次显示启动成功了,但是实际上并没有
```
D:\work_project\docker\oceanbase>docker compose up
[+] Running 2/2
 ✔ Network oceanbase_default  Created                                                                              0.3s
 ✔ Container oceanbase-ce     Created                                                                              0.1s
Attaching to oceanbase-ce
oceanbase-ce  | do normal boot
oceanbase-ce  | oceanbase-ce-4.3.5.1 already installed.
oceanbase-ce  | +--------------------------------------------------------------------------------------------+
oceanbase-ce  | |                                          Packages                                          |
oceanbase-ce  | +--------------+---------+------------------------+------------------------------------------+
oceanbase-ce  | | Repository   | Version | Release                | Md5                                      |
oceanbase-ce  | +--------------+---------+------------------------+------------------------------------------+
oceanbase-ce  | | oceanbase-ce | 4.3.5.1 | 101000042025031818.el8 | 3a4f23adb7973d6d1d6969bcd9ae108f8c564b66 |
oceanbase-ce  | +--------------+---------+------------------------+------------------------------------------+
oceanbase-ce  | Repository integrity check ok
oceanbase-ce  | Load param plugin ok
oceanbase-ce  | Open ssh connection ok
oceanbase-ce  | Initializes observer work home ok
oceanbase-ce  | Parameter check ok
oceanbase-ce  | Remote oceanbase-ce-4.3.5.1-101000042025031818.el8-3a4f23adb7973d6d1d6969bcd9ae108f8c564b66 repository install ok
oceanbase-ce  | Remote oceanbase-ce-4.3.5.1-101000042025031818.el8-3a4f23adb7973d6d1d6969bcd9ae108f8c564b66 repository lib check !!
oceanbase-ce  | Try to get lib-repository
oceanbase-ce  | oceanbase-ce-libs-4.3.5.1 already installed.
oceanbase-ce  | Remote oceanbase-ce-libs-4.3.5.1-101000042025031818.el8-99da58cec7132bb3f538ef0a7dc844eb07ab6d05 repository install ok
oceanbase-ce  | Remote oceanbase-ce-4.3.5.1-101000042025031818.el8-3a4f23adb7973d6d1d6969bcd9ae108f8c564b66 repository lib check ok
oceanbase-ce  | obcluster deployed
oceanbase-ce  | Please execute ` obd cluster start obcluster ` to start
oceanbase-ce  | Trace ID: fb75c758-20ac-11f0-8f75-0242ac130002
oceanbase-ce  | If you want to view detailed obd logs, please run: obd display-trace fb75c758-20ac-11f0-8f75-0242ac130002
Get local repositories ok
oceanbase-ce  | Load cluster param plugin ok
oceanbase-ce  | Open ssh connection ok
oceanbase-ce  | [WARN] OBD-1011: (172.19.0.2) The recommended value of fs.aio-max-nr is 1048576 (Current value: 65536)
oceanbase-ce  | [WARN] OBD-1017: (172.19.0.2) The value of the "vm.max_map_count" must be within [327600, 1310720] (Current value: 262144, Recommended value: 655360)
oceanbase-ce  | [WARN] OBD-1017: (172.19.0.2) The value of the "vm.overcommit_memory" must be 0 (Current value: 1, Recommended value: 0)
oceanbase-ce  | [WARN] OBD-1012: (172.19.0.2) clog and data use the same disk (/root/ob)
oceanbase-ce  | cluster scenario: express_oltp
oceanbase-ce  | Start observer ok
oceanbase-ce  | observer program health check x
oceanbase-ce  | [WARN] OBD-2002: Failed to start 172.19.0.2 observer
oceanbase-ce  | See https://www.oceanbase.com/product/ob-deployer/error-codes .
oceanbase-ce  | Trace ID: fe663272-20ac-11f0-b263-0242ac130002
oceanbase-ce  | If you want to view detailed obd logs, please run: obd display-trace fe663272-20ac-11f0-b263-0242ac130002
boot failed!  |
oceanbase-ce exited with code 0
oceanbase-ce  | Get local repositories ok
oceanbase-ce  | Load cluster param plugin ok
oceanbase-ce  | Open ssh connection ok
oceanbase-ce  | [WARN] OBD-1011: (172.19.0.2) The recommended value of fs.aio-max-nr is 1048576 (Current value: 65536)
oceanbase-ce  | [WARN] OBD-1017: (172.19.0.2) The value of the "vm.max_map_count" must be within [327600, 1310720] (Current value: 262144, Recommended value: 655360)
oceanbase-ce  | [WARN] OBD-1017: (172.19.0.2) The value of the "vm.overcommit_memory" must be 0 (Current value: 1, Recommended value: 0)
oceanbase-ce  | [WARN] OBD-1012: (172.19.0.2) clog and data use the same disk (/root/ob)
oceanbase-ce  | cluster scenario: express_oltp
oceanbase-ce  | Start observer ok
oceanbase-ce  | observer program health check x
oceanbase-ce  | [WARN] OBD-2002: Failed to start 172.19.0.2 observer
oceanbase-ce  | See https://www.oceanbase.com/product/ob-deployer/error-codes .
oceanbase-ce  | Trace ID: 0267621a-20ad-11f0-aeb3-0242ac130002
oceanbase-ce  | If you want to view detailed obd logs, please run: obd display-trace 0267621a-20ad-11f0-aeb3-0242ac130002
boot success! |
```

不映射数据卷的时候:
```
D:\work_project\docker\oceanbase>docker compose up
[+] Running 2/2
 ✔ Network oceanbase_default  Created                                                                              0.2s
 ✔ Container oceanbase-ce     Created                                                                              0.1s
Attaching to oceanbase-ce
oceanbase-ce  | do normal boot
oceanbase-ce  | oceanbase-ce-4.3.5.1 already installed.
oceanbase-ce  | +--------------------------------------------------------------------------------------------+
oceanbase-ce  | |                                          Packages                                          |
oceanbase-ce  | +--------------+---------+------------------------+------------------------------------------+
oceanbase-ce  | | Repository   | Version | Release                | Md5                                      |
oceanbase-ce  | +--------------+---------+------------------------+------------------------------------------+
oceanbase-ce  | | oceanbase-ce | 4.3.5.1 | 101000042025031818.el8 | 3a4f23adb7973d6d1d6969bcd9ae108f8c564b66 |
oceanbase-ce  | +--------------+---------+------------------------+------------------------------------------+
oceanbase-ce  | Repository integrity check ok
oceanbase-ce  | Load param plugin ok
oceanbase-ce  | Open ssh connection ok
oceanbase-ce  | Initializes observer work home ok
oceanbase-ce  | Parameter check ok
oceanbase-ce  | Remote oceanbase-ce-4.3.5.1-101000042025031818.el8-3a4f23adb7973d6d1d6969bcd9ae108f8c564b66 repository install ok
oceanbase-ce  | Remote oceanbase-ce-4.3.5.1-101000042025031818.el8-3a4f23adb7973d6d1d6969bcd9ae108f8c564b66 repository lib check !!
oceanbase-ce  | Try to get lib-repository
oceanbase-ce  | oceanbase-ce-libs-4.3.5.1 already installed.
oceanbase-ce  | Remote oceanbase-ce-libs-4.3.5.1-101000042025031818.el8-99da58cec7132bb3f538ef0a7dc844eb07ab6d05 repository install ok
oceanbase-ce  | Remote oceanbase-ce-4.3.5.1-101000042025031818.el8-3a4f23adb7973d6d1d6969bcd9ae108f8c564b66 repository lib check ok
oceanbase-ce  | obcluster deployed
oceanbase-ce  | Please execute ` obd cluster start obcluster ` to start
oceanbase-ce  | Trace ID: 40658c9a-20ad-11f0-b8a4-0242ac130002
oceanbase-ce  | If you want to view detailed obd logs, please run: obd display-trace 40658c9a-20ad-11f0-b8a4-0242ac130002
Get local repositories ok
oceanbase-ce  | Load cluster param plugin ok
oceanbase-ce  | Open ssh connection ok
oceanbase-ce  | [WARN] OBD-1011: (172.19.0.2) The recommended value of fs.aio-max-nr is 1048576 (Current value: 65536)
oceanbase-ce  | [WARN] OBD-1017: (172.19.0.2) The value of the "vm.max_map_count" must be within [327600, 1310720] (Current value: 262144, Recommended value: 655360)
oceanbase-ce  | [WARN] OBD-1017: (172.19.0.2) The value of the "vm.overcommit_memory" must be 0 (Current value: 1, Recommended value: 0)
oceanbase-ce  | [WARN] OBD-1012: (172.19.0.2) clog and data use the same disk (/)
oceanbase-ce  | cluster scenario: express_oltp
oceanbase-ce  | Start observer ok
oceanbase-ce  | observer program health check ok
oceanbase-ce  | Connect to observer ok
oceanbase-ce  | oceanbase bootstrap ok
oceanbase-ce  | obshell start ok
oceanbase-ce  | obshell program health check ok
oceanbase-ce  | obshell bootstrap ok
oceanbase-ce  | Connect to observer ok
oceanbase-ce  | Wait for observer init ok
oceanbase-ce  | +----------------------------------------------+
oceanbase-ce  | |                 oceanbase-ce                 |
oceanbase-ce  | +------------+---------+------+-------+--------+
oceanbase-ce  | | ip         | version | port | zone  | status |
oceanbase-ce  | +------------+---------+------+-------+--------+
oceanbase-ce  | | 172.19.0.2 | 4.3.5.1 | 2881 | zone1 | ACTIVE |
oceanbase-ce  | +------------+---------+------+-------+--------+
oceanbase-ce  | obclient -h172.19.0.2 -P2881 -uroot@sys -Doceanbase -A
oceanbase-ce  |
oceanbase-ce  | cluster unique id: a88573b4-11e8-5e49-adce-e1eb21087aeb-19665755d97-01050304
oceanbase-ce  |
oceanbase-ce  | obcluster running
oceanbase-ce  | Trace ID: 427bfe9c-20ad-11f0-a07e-0242ac130002
oceanbase-ce  | If you want to view detailed obd logs, please run: obd display-trace 427bfe9c-20ad-11f0-a07e-0242ac130002
Get local repositories ok
oceanbase-ce  | Open ssh connection ok
oceanbase-ce  | Connect to observer ok
oceanbase-ce  | Create tenant test ok
oceanbase-ce  | Exec oceanbase-ce-4.3.5.1-101000042025031818.el8-3a4f23adb7973d6d1d6969bcd9ae108f8c564b66 import_time_zone_info.py ok
oceanbase-ce  | Exec oceanbase-ce-4.3.5.1-101000042025031818.el8-3a4f23adb7973d6d1d6969bcd9ae108f8c564b66 import_srs_data.py ok
oceanbase-ce  | obclient -h172.19.0.2 -P2881 -uroot@test -Doceanbase -A
oceanbase-ce  |
oceanbase-ce  | optimize tenant with scenario: express_oltp ok
oceanbase-ce  | Trace ID: 57003c20-20ad-11f0-ad27-0242ac130002
oceanbase-ce  | If you want to view detailed obd logs, please run: obd display-trace 57003c20-20ad-11f0-ad27-0242ac130002
check tenant connectable
oceanbase-ce  | tenant is connectable
oceanbase-ce  | boot success!
```
      
为什么不建议使用,有时候数据很少,就是mysql的平替而已,甚至多租户功能都不需要:

![Image](https://github.com/user-attachments/assets/b28547d0-bbc3-425f-bb7d-c2b496be1501)

### Environment

windows 的最新 docker-desktop

### Fast reproduce steps

100%复现,使用我上面的docker-compose.yml

### Expected behavior

映射数据卷应该启动成功的吧?
